### PR TITLE
Fix #84 Make a separate "Web App" version

### LINKED ISSUE #84: Make a separate "Web App" version
It should contain a minimal set of styles suitable for being a base stylesheet for a Web app.

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
Fix #84

### CODE REVIEW

**Comment by Aulakh22** [comment]
Hello 
I am using this <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" /> link but it is not working properly. 
What can I do for this.

**Comment by Aulakh22** [comment]
link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" /

**Comment by EvgenyOrekhov** [comment]
@Aulakh22 Please create a separate issue and describe your problem in more detail.

**Comment by EvgenyOrekhov** [comment]
This is too old.

**Pull request closed without merging**
